spring:
  application:
    name: user- service

  datasource:
    url: jdbc:postgresql://localhost:5432/fitness-tut-users
    username: postgres
    password: newpassword

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/